version: 0.0
os: linux
files:
 - source: /
    destination: /home/ec2-user/express-app
hooks:
  ApplocationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 3000
      runas: ec2-user
  ApplicationStart:
    - location: scripts/application_start.sh  
      timeout: 3000
      runas: ec2-user  
      
      
  - name: Sourcetoad - AWS CodeDeploy for GitHub Actions
    uses: sourcetoad/aws-codedeploy-action@v1.3.0
